version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: mi_apache
    ports:
      - "8080:80"
    volumes:
      - ./apache:/usr/local/apache2/htdocs
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mi_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mi_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
